spring.application.name=hospitalManagement
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/hospital_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Soumen!098
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate settings (Optional but recommended)
# 'update' automatically creates/updates tables based on your Java entities
spring.jpa.hibernate.ddl-auto=create
 spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql